# Generated by Django 2.1.5 on 2021-09-10 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reunion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='docente',
            field=models.ForeignKey(db_column='docente', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
