# Generated by Django 2.1.5 on 2021-09-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0002_auto_20210920_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carnet_identidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='item',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rude',
            field=models.IntegerField(default=0),
        ),
    ]
