# Generated by Django 2.1.5 on 2021-09-10 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reunion', '0002_aula_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='docente',
        ),
        migrations.AddField(
            model_name='aula',
            name='moderador',
            field=models.ForeignKey(db_column='moderador', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moderador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
