# Generated by Django 2.1.5 on 2021-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0003_auto_20210922_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=2),
        ),
    ]
