# Generated by Django 2.1.5 on 2021-09-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0004_auto_20210922_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default='2e3', max_length=200),
            preserve_default=False,
        ),
    ]
