# Generated by Django 2.1.5 on 2021-09-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0005_usuario_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='encargado',
            field=models.ForeignKey(db_column='encargado', on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to='reunion.Usuario'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='miembros',
            field=models.ManyToManyField(to='reunion.Usuario'),
        ),
    ]
