# Generated by Django 2.1.5 on 2021-09-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0006_auto_20210924_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='entidad',
            field=models.ForeignKey(db_column='entidad', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entidad', to='reunion.Entidad'),
            preserve_default=False,
        ),
    ]
