# Generated by Django 2.1.5 on 2021-09-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0008_auto_20210928_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='moderador',
            field=models.ForeignKey(db_column='moderador', on_delete=django.db.models.deletion.CASCADE, related_name='moderador', to='reunion.Usuario'),
        ),
    ]
