# Generated by Django 2.1.5 on 2021-09-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0009_auto_20210928_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='miembros',
            field=models.ManyToManyField(to='reunion.Usuario'),
        ),
    ]
