# Generated by Django 3.2.5 on 2021-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbluebutton', '0006_remove_bbbmeeting_create_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbbmeeting',
            name='attendeePW',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bbbmeeting',
            name='moderatorPW',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bbbmeeting',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
