# Generated by Django 2.1.5 on 2021-10-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0010_auto_20210928_2150'),
        ('bigbluebutton', '0007_auto_20210709_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbmeeting',
            name='aula',
            field=models.ManyToManyField(to='reunion.Sala'),
        ),
    ]
