# Generated by Django 2.1.5 on 2021-10-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigbluebutton', '0008_bbbmeeting_aula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbbmeeting',
            old_name='aula',
            new_name='sala',
        ),
    ]
