# Generated by Django 2.1.5 on 2021-10-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigbluebutton', '0009_auto_20211005_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbbmeeting',
            old_name='sala',
            new_name='salas',
        ),
    ]
