# Generated by Django 2.1.5 on 2021-10-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0010_auto_20210928_2150'),
        ('bigbluebutton', '0010_auto_20211005_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbmeeting',
            name='moderador',
            field=models.ForeignKey(db_column='moderador_reunion', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moderador_reunion', to='reunion.Usuario'),
            preserve_default=False,
        ),
    ]
